[[redirects]]
  from = "/"
  to = "https://github.com/strubloid"
  status = 301
  force = true

[[redirects]]
  from = "/book"
  to = "https://github.com/strubloid/mygitbook"
  status = 301
  force = true

[[redirects]]
  from = "/.bash_aliases"
  to = "https://github.com/strubloid/.bash_aliases"
  status = 301
  force = true

[[redirects]]
  from = "/strubloid-on-nextjs"
  to = "https://github.com/strubloid/strubloid-on-nextjs"
  status = 301
  force = true

